name = "streak-fastapi"
main = "main.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2025-03-16"

[observability.logs]
enabled = true

[[rules]]
globs = ["vendor/**"]
type = "Data"
fallthrough = true